services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${FRONTEND_CONTAINER_NAME:-frontend-container}
    ports:
      - "${FRONTEND_PORT_LOCAL}:3000"
    restart: unless-stopped
